---
title: "Loading NOAA Data - West Central GA"
author: "EPatton"
date: "2023-01-09"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(lubridate)
install.packages('dyplr')
library(dplyr)
```
```{r CREATE AND READ IN NOAA WEST CENTRAL GA DATA SET - DAILY HIGH TEMP}
#write_csv(NOAA_GA_WestCentral, "/Users/erikpatton/Library/Mobile Documents/com~apple~CloudDocs/Duke/Data_Dissertation/Raw Data/NOAA_GA_WestCentral.csv")
#write_csv(STATION_Missing.Years, "/Users/erikpatton/Library/Mobile Documents/com~apple~CloudDocs/Duke/Data_Dissertation/Raw Data/NOAA_GA_WestCentral_MissingYears.csv")
NOAA_Raw <- read.csv("/Users/erikpatton/Library/Mobile Documents/com~apple~CloudDocs/Duke/Data_Dissertation/Raw Data/NOAA_GA_WestCentral.csv")
NOAA_Raw_MissingYears <- read.csv("/Users/erikpatton/Library/Mobile Documents/com~apple~CloudDocs/Duke/Data_Dissertation/Raw Data/NOAA_GA_WestCentral_MissingYears.csv")
```

```{r}
##create a name for the full data set and bind the missing data piece(s)
NOAA_GA_WestCentral <- NOAA_Raw
NOAA_GA_WestCentral <- rbind(NOAA_GA_WestCentral, NOAA_Raw_MissingYears)
##select needed columns and remove duplicates
GA_NOAA_Wrangled <- NOAA_GA_WestCentral %>%
  select(NAME, DATE, TMAX)%>%
  distinct()%>%
  arrange(ymd(DATE))

GA_NOAA_Wrangled$DATE <- as_date(GA_NOAA_Wrangled$DATE)
#view(GA_NOAA_Wrangled)

GA_NOAA_Wrangled_Wide <- pivot_wider(GA_NOAA_Wrangled,names_from = NAME, values_from = TMAX)
view(GA_NOAA_Wrangled_Wide)

#class(GA_NOAA_Wrangled_Wide$`SUNNYSIDE, GA US`)
#GA_NOAA_Wrangled_Wide$`SUNNYSIDE, GA US`[3]+GA_NOAA_Wrangled_Wide$`SUNNYSIDE, GA US`[4]
#sum(GA_NOAA_Wrangled_Wide[2:141])

#GA_NOAA_Wide3 <-  GA_NOAA_Wrangled_Wide[2:15979,2:141] %>%                        
#  replace(is.na(.), 0) %>%
#  mutate(sum = rowSums(.))
#view(GA_NOAA_Wide3)
```


```{r TRY AND GET AVERAGE HIGH TEMPARTURES PER DAY - THE AVERAGE FOR THE GEORGIA WEST CENTRAL REPORTING DISTRICT (i.e. where FBGA is located)}

#rowMeans(GA_NOAA_Wrangled_Wide[,2:141])
##Create a new column with the average temperature of all stations that reported for that date
GA_NOAA_Wrangled_Wide$Row_AVG <- rowMeans(GA_NOAA_Wrangled_Wide[,2:141],na.rm=TRUE)
#view(GA_NOAA_Wrangled_Wide)
#view(GA_NOAA_Wrangled_Wide$Row_AVG)

GA_NOAA_Wrangled_Wide <- GA_NOAA_Wrangled_Wide%>%
  select(DATE,Row_AVG)%>%
  mutate(Row_AVG.C = ((Row_AVG-32)*(5/9)))%>%
  rename(date=DATE)

#Join all three main data sets to the same NOAA data set (NOAA data set is most complete)
GA_NOAA_Wrangled_Wide <-  full_join(GA_NOAA_Wrangled_Wide,KLSF_Daily_High.C_Clean,by="date")
GA_NOAA_Wrangled_Wide <- GA_NOAA_Wrangled_Wide%>%
  select(date,Row_AVG.C,High.C_Clean)%>%
  rename(KLSF.C=High.C_Clean)
GA_NOAA_Wrangled_Wide <- full_join(GA_NOAA_Wrangled_Wide,KCSG_Daily_High.C_Clean,by="date")
GA_NOAA_Wrangled_Wide <- GA_NOAA_Wrangled_Wide%>%
  select(date,Row_AVG.C,KLSF.C,High.C_Clean)%>%
  rename(KCSG.C=High.C_Clean)
view(GA_NOAA_Wrangled_Wide)
```

```{r}
```{r PLOT THE THREE DAILY HIGH TEMPERATURES}
GA_Daily_High.C <- GA_NOAA_Wrangled_Wide
GA_Daily_High.C.plot <- ggplot(GA_Daily_High.C, aes(x=date))+
  geom_line(aes(y=KLSF.C, color='blue'), size=0.2)+
  geom_line(aes(y=KCSG.C,color='red'),linewidth=0.2)+
  geom_line(aes(y=Row_AVG.C,color='white'),linewidth=0.2)
GA_Daily_High.C.plot

##SUBSECTION FOR LAST TEN YEARS
GA_Daily_High.C._Last10Year <- GA_Daily_High.C%>%
  filter(date>="2012-01-01", date<="2018-01-01")
  
GA_Daily_High.C.plot_10Year <- ggplot(GA_Daily_High.C._Last10Year, aes(x=date))+
  geom_line(aes(y=KLSF.C, color='blue'), size=0.2)+
  geom_line(aes(y=KCSG.C,color='red'),linewidth=0.2)+
  geom_line(aes(y=Row_AVG.C,color='white'),linewidth=0.2)
GA_Daily_High.C.plot_10Year
```
```


```{r PLOT THE INITIAL DATA POINTS TO CHECK FOR COMPLETENESS}
ggplot(GA_NOAA_Wrangled_Wide)+
  geom_point(aes(x=DATE,y=Row_AVG))
```
```{r PLOT DATA POINTS IN A USABLE FORMAT}
ggplot(GA_NOAA_Wrangled_Wide)+
  geom_line(aes(x=DATE,y=Row_AVG))
```
#### CREATE A PLOT OF HOURS PER YEAR ABOVE 88F (ROUGHLY ANALOGUS TO RED FLAG CATAGORY)
```{r}
GA_DaysAbove88.F <- GA_NOAA_Wrangled_Wide %>%
  filter(DATE >= '1973-01-01') %>%
  select(DATE,Row_AVG)%>%
  mutate('Year' = year(DATE))%>%
  subset(Row_AVG >= '88') %>%
  group_by(Year) %>%
  count(Year) %>%
  rename(Hours_Above_88F = n)

ggplot(GA_DaysAbove88.F)+
  geom_line(aes(x=Year,y=Hours_Above_88F))
```

